[package]
name = "nosh"
version = "0.1.0"
authors = ["Skyler Berg <skylertheberg@gmail.com>"]

[dependencies]
lazy_static = "0.1.*"

[dependencies.readline]
git = "https://github.com/shaleh/rust-readline.git"

[dev-dependencies]
tempdir = "0.3"
